# Generated by Django 5.1.3 on 2025-01-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_chat_group_admin_chat_group_admins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='group_admins',
            new_name='group_admin',
        ),
    ]
